---
- name: Adding environment variable in bashrc file
  blockinfile:
    dest: /home/{{ hadoop_user }}/.bashrc 
    block: |
      #HADOOP VARIABLES START
      export JAVA_HOME=/usr/lib/jvm/java-8-oracle
      export PATH=$PATH:$JAVA_HOME/bin
      export HADOOP_HOME={{ hadoop_home_dir }}
      export PATH=$PATH:$HADOOP_HOME/bin
      export PATH=$PATH:$HADOOP_HOME/sbin
      export HADOOP_MAPRED_HOME=$HADOOP_HOME
      export HADOOP_COMMON_HOME=$HADOOP_HOME
      export HADOOP_HDFS_HOME=$HADOOP_HOME
      export YARN_HOME=$HADOOP_HOME
      export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
      export HADOOP_OPTS="$HADOOP_OPTS -Djava.library.path=$HADOOP_HOME/lib/native"
      export CLASSPATH=$CLASSPATH:/usr/local/hadoop/lib/*:.
      export HADOOP_OPTS="$HADOOP_OPTS -Djava.security.egd=file:{{ hadoop_home_dir }}/temp/tmp"
      #HADOOP VARIABLES END

- name: Executnge source command
  shell: ". /home/{{ hadoop_user }}/.bashrc"


