- include: cluster-setup.yml
  when: hadoop_install_mode == 'cluster'
- include: single-node-setup.yml
  when: hadoop_install_mode == 'single' and ansible_fqdn == "{{ hadoop_namenode }}"
- include: datanode-setup.yml
  when: hadoop_install_mode == 'datanode' and inventory_hostname in "{{ groups['newdatanode'] }}"
