---
#THIS FILE WILL CREATE REQUIRED DIRECTORIES AND PATH
# CHECKING DOWNLOADING DIRECTORY PRESENT OR NOT
- name: Check install directory present or not
  stat: path={{ pkg_install_dir }}
  register: location
- name: Creating install directory if not present
  file:
    path: "{{ pkg_install_dir }}"
    state: directory
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    recurse: yes
    mode: 0755
  when: location.stat.exists == false

#CHECKING HADOOP STORE DIRECTORY PRESENT OR NOT
- name: Check store directory present or not
  stat: path={{ ha_store_dir }}
  register: store
- name: Creating store directory if not present
  file: 
    path: "{{ ha_store_dir }}"
    state: directory
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    recurse: yes
    mode: 0755
  when: store.stat.exists == false

#CREATING USER GROUP IF NOT EXISTING
- name: Creating user group if not exists
  group: name={{ ha_group }}  state=present
- name: Creating user if not exists
  user: 
    name: "{{ ha_user }}"
    shell: /bin/bash 
    group: "{{ ha_group }}" 
    append: yes

#CREATING JOURNALNODE DATA DIRECTORY
- name: Checking journalnode is present or not
  stat: path={{ journalnode_data_dir }}
  register: journal
  when: inventory_hostname in groups[zoo_nodes]
- name: Creating journalnode directory if not present
  file:
    path: "{{ journalnode_data_dir }}"
    state: directory
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    recurse: yes
    mode: 0755
  when: journal.stat.exists == false and inventory_hostname in groups[zoo_nodes]

#CREATING ZOOKEEPER DATA DIRECTORY
- name: Checking zookeeper data directory present or not
  stat: path={{ zookeeper_data_dir }}
  register: zookeeper
  when: inventory_hostname in groups[zoo_nodes]
- name: Creating zookeeper data directory
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    recurse: yes
    mode: 0755
  when: zookeeper.stat.exists == false and inventory_hostname in groups[zoo_nodes]

#CREATING NAMENODE DIRECTORY IN NAMENODE SERVERS
- name: Creating namenode directory in namenode-1
  file:
    path: "{{ ha_store_dir }}/hdfs/namenode"
    state: directory
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    mode: 0755
    recurse: yes
  when: ansible_fqdn == ha_namenode1

- name: Creating namenode directory in namenode-2
  file:
    path: "{{ ha_store_dir }}/hdfs/namenode"
    state: directory
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    mode: 0755
    recurse: yes
  when: ansible_fqdn == ha_namenode2

#CREATING DATANODE DATA DIRECTORY IN ALL DATANODE
- name: Creating datanode directory
  file:
    path: "{{ ha_store_dir }}/hdfs/datanode"
    state: directory
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    mode: 0755
    recurse: yes
  when: ansible_fqdn != ha_namenode1 and ansible_fqdn != ha_namenode2

#CREATING TEMPORARY DIRECTORY IN ALL SERVERS
- name: Creating temporaray directory
  file:
    path: "{{ ha_store_dir }}/tmp"
    state: directory
    owner: "{{ ha_user }}"
    group: "{{ ha_group }}"
    mode: 0755
    recurse: yes

