---
#CONFIGURATION FOR STARTING JOURNALNODES IN ZOOKEEPER SERVER

#Starting Journal nodes only in zookeeper servers
- name: Starting Journalnode servers
  command: "{{ ha_home_dir }}/sbin/hadoop-daemon.sh start journalnode"
  become: True
  become_user: "{{ ha_user }}"
  when: inventory_hostname in groups[zoo_nodes]

#Formating second namenode
- name: Formating the namenode servers-2
  command: "{{ ha_home_dir }}/bin/hdfs namenode -format -force"
  become: True
  become_user: "{{ ha_user }}"
  when: ansible_fqdn == ha_namenode2

- name: Foramating the namenode servers-1
  command: "{{ ha_home_dir }}/bin/hdfs namenode -format -force"
  become: True
  become_user: "{{ ha_user }}"
  when: ansible_fqdn == ha_namenode1

- name: Starting namenode servers
  command: "{{ ha_home_dir }}/sbin/hadoop-daemon.sh start namenode"
  become: True
  become_user: "{{ ha_user }}"
  when: inventory_hostname in groups[namenode_group]

- name: Start bootstrap process in namenode2
  command: "{{ ha_home_dir }}/bin/hdfs namenode -bootstrapStandby -force"
  become: True
  become_user: "{{ ha_user }}"
  when: ansible_fqdn == ha_namenode2

- name: Start zookeeper daemon in all zookeeper servers
  command: "{{ zoo_home_dir }}/bin/zkServer.sh start"
  become: True
  become_user: "{{ ha_user }}"
  when: inventory_hostname in groups[zoo_nodes]

- name: Format zookeeper failovercontroller in namenode-2
  command: "{{ ha_home_dir }}/bin/hdfs zkfc -formatZK -force"
  become: True
  become_user: "{{ ha_user }}"
  when: ansible_fqdn == ha_namenode2

- name: Start failover controler in namenode-2
  command: "{{ ha_home_dir }}/sbin/hadoop-daemon.sh start zkfc"
  become: True
  become_user: "{{ ha_user }}"
  when: ansible_fqdn == ha_namenode2

- name: Format zookeeper failovercontroller in namenode-1
  command: "{{ ha_home_dir }}/bin/hdfs zkfc -formatZK -force"
  become: True
  become_user: "{{ ha_user }}"
  when: ansible_fqdn == ha_namenode1

- name: Start failover controler in namenode-1
  command: "{{ ha_home_dir }}/sbin/hadoop-daemon.sh start zkfc"
  become: True
  become_user: "{{ ha_user }}"
  when: ansible_fqdn == ha_namenode1

- name: Starting namenode servers for failovercontroller
  command: "{{ ha_home_dir }}/sbin/hadoop-daemon.sh start namenode"
  become: True
  become_user: "{{ ha_user }}"
  when: ansible_fqdn == ha_namenode2

- name: Starting datanodes
  command: "{{ ha_home_dir }}/sbin/hadoop-daemon.sh start datanode"
  become: True
  become_user: "{{ ha_user }}"
  when: inventory_hostname in groups[datanode_group]

