---
#Linking service script
- name: "Checking file is present or not"
  stat:
    path: "{{ amq_home_dir }}/bin/linux-x86-{{ ansible_userspace_bits }}/"
  register: value
- debug: var=value.stat
- name: "Set fact if directory is available"
  set_fact:
    amq_directory: true
  when: value.stat.exists

#Copying service template to activemq folder
- name: "Copying service script-1 to server"
  template:
    src: activemq.j2 
    dest: "{{ amq_home_dir }}/bin/linux-x86-{{ ansible_userspace_bits }}/activemq"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
    mode: 0755
  when: amq_directory is defined
#Copying wrapper file to activemq folder
- name: "Copying wrapper  file"
  template:
    src: wrapper.conf.j2
    dest: "{{ amq_home_dir }}/bin/linux-x86-{{ ansible_userspace_bits }}/wrapper.conf"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
    mode: 0644
  when: amq_directory is defined

- name: "Create a link to init.d"
  file:
    src: "{{ amq_home_dir }}/bin/linux-x86-{{ ansible_userspace_bits }}/activemq"
    dest: "/etc/init.d/activemq"
    owner: root
    group: root
    state: link
  when: amq_directory is defined

- name: "Enable aactivemq service"
  command: update-rc.d activemq defaults
  become: yes
  become_method: sudo
