---
- stat: path={{ amq_install_dir }}/apache-activemq-{{ amq_version }}
  register: result

- debug: msg="Path exists and a directory"
- name: going to start amq
  command: "{{ amq_home_dir }}/bin/activemq start"
  when: amq_service == "no"

- name: "Starting amq with service command"
  service: name=activemq enabled=yes state=started
  when: amq_service == "yes"
