---
#Checking python3.5 is already installed or not
- name: Testing if python3.5 is already installed
  command: python3.5 --version
  register: python_status
  ignore_errors: true

- name: Add python repo
  apt_repository:
    repo: "{{ apt_python_repo }}"
    state: present
    update_cache: yes
  when: python_status.rc != 0

- name: Install python3.5
  apt:
    name: "{{ apt_python_package }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  when: python_status.rc != 0

- name: Install pip3.5
  apt:
    name: python3-pip
    state: present

#Upgrade pip3 to pip3.5
- name: Upgrading pip3 to pip3.5
  command: "pip3 install --upgrade pip"
  become: True
  become_method: sudo
