docker_edition: ce
docker_channel: ["stable"]
docker_version: 5:19.03.5
docker_state: present
docker_package_dependencies:
  - "apt-transport-https"
  - "ca-certificates"
  - "gnupg2"
  - "curl"
  - "software-properties-common"

docker_pip_dependencies:
  - "python-setuptools"
  - "python{{ '3' if ansible_python.version.major == 3 else '' }}-pip"

#pip pacakages to install
#  - "docker-py"
docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_apt_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker_apt_repository: >
  deb [arch=amd64]
  https://download.docker.com/linux/{{ ansible_distribution | lower }}
  {{ ansible_distribution_release }} {{ docker_channel | join (' ') }}
docker_users: ["ubuntu","arjun"]

#swarm-componets
docker_swarm_advertise_addrs: 127.0.0.1
